#!/bin/bash
set -euxo pipefail

release_dir="$(dirname "$0")/.."

rm -r "${release_dir}/src/otel-collector"

pushd "${release_dir}/src/otel-collector-builder"
  go run go.opentelemetry.io/collector/cmd/builder --skip-compilation --config=config.yaml
popd

pushd "${release_dir}/src/otel-collector"
  go get toolchain@none
  go mod vendor
popd

pushd "${release_dir}/src/integration"
  go mod tidy
  go mod vendor
popd
